#配置服务器访问端口和字符编码
server:
  port: 80
  servlet:
    encoding:
      charset: UTF-8

#数据库连接信息 使用druid数据源
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/task0427
      username: root
      password: 123456

#配置mybatis映射文件和日志
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

